set(_CATKIN_CURRENT_PACKAGE "robosub_simulator")
set(robosub_simulator_VERSION "0.0.0")
set(robosub_simulator_MAINTAINER "Jason Lunder <jlunder@zagmail.gonzaga.edu>, Eric Av <eav@zagmail.gonzaga.edu>")
set(robosub_simulator_PACKAGE_FORMAT "1")
set(robosub_simulator_BUILD_DEPENDS "gazebo_ros" "roscpp" "rospy" "gazebo_ros" "gazebo_plugins" "gazebo_msgs" "std_msgs" "message_generation")
set(robosub_simulator_BUILD_EXPORT_DEPENDS "gazebo_ros" "roscpp" "rospy" "gazebo_ros" "gazebo_plugins" "gazebo_msgs" "std_msgs" "message_generation")
set(robosub_simulator_BUILDTOOL_DEPENDS "catkin")
set(robosub_simulator_BUILDTOOL_EXPORT_DEPENDS )
set(robosub_simulator_EXEC_DEPENDS "gazebo_ros" "roscpp" "rospy" "gazebo_ros" "gazebo_plugins" "gazebo_msgs" "std_msgs" "message_generation")
set(robosub_simulator_RUN_DEPENDS "gazebo_ros" "roscpp" "rospy" "gazebo_plugins" "gazebo_msgs" "std_msgs" "message_generation")
set(robosub_simulator_TEST_DEPENDS )
set(robosub_simulator_DOC_DEPENDS )
set(robosub_simulator_URL_WEBSITE "")
set(robosub_simulator_URL_BUGTRACKER "")
set(robosub_simulator_URL_REPOSITORY "")
set(robosub_simulator_DEPRECATED "")